### ISSUE TITLE
Container not starting 

### ISSUE THREAD

**Issue by SteynGuelen** [loganmarchione/docker-speedtest-influxdb#9]
Hi, when running the container for the first time, I receive this error: 
```
 #####
Script starting!
#####
STATE: Starting at 2022-12-18T20:23:32.686625
STATE: Sleep time between runs set to 60 seconds
STATE: Loop running at 2022-12-18T20:23:32.686655
STATE: Speedtest running
==============================================================================
You may only use this Speedtest software and information generated
from it for personal, non-commercial use, through a command line
interface on a personal computer. Your use of this software is subject
to the End User License Agreement, Terms of Use and Privacy Policy at
these URLs:
        https://www.speedtest.net/about/eula
        https://www.speedtest.net/about/terms
        https://www.speedtest.net/about/privacy
==============================================================================
License acceptance recorded. Continuing.
==============================================================================
Ookla collects certain data through Speedtest that may be considered
personally identifiable, such as your IP address, unique device
identifiers or location. Ookla believes it has a legitimate interest
to share this data with internet providers, hardware manufacturers and
industry regulators to help them understand and create a better and
faster internet. For further information including how the data may be
shared, where the data may be transferred and Ookla's contact details,
please see our Privacy Policy at:
       http://www.speedtest.net/privacy
==============================================================================
To accept the message please run speedtest interactively or use the following:
    speedtest --accept-gdpr
Traceback (most recent call last):
  File "./speedtest.py", line 95, in <module>
    loop()
  File "./speedtest.py", line 33, in loop
    my_speed = subprocess.run(['/usr/bin/speedtest', '--accept-license', '--format=json'], stdout=subprocess.PIPE, text=True, check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/speedtest', '--accept-license', '--format=json']' returned non-zero exit status 1.
#####
Script starting!
#####
STATE: Starting at 2022-12-18T20:25:20.577497
STATE: Sleep time between runs set to 60 seconds
STATE: Loop running at 2022-12-18T20:25:20.577526
STATE: Speedtest running
==============================================================================
Ookla collects certain data through Speedtest that may be considered
personally identifiable, such as your IP address, unique device
identifiers or location. Ookla believes it has a legitimate interest
to share this data with internet providers, hardware manufacturers and
industry regulators to help them understand and create a better and
faster internet. For further information including how the data may be
shared, where the data may be transferred and Ookla's contact details,
please see our Privacy Policy at:
       http://www.speedtest.net/privacy
==============================================================================
To accept the message please run speedtest interactively or use the following:
    speedtest --accept-gdpr
Traceback (most recent call last):
  File "./speedtest.py", line 95, in <module>
    loop()
  File "./speedtest.py", line 33, in loop
    my_speed = subprocess.run(['/usr/bin/speedtest', '--accept-license', '--format=json'], stdout=subprocess.PIPE, text=True, check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/speedtest', '--accept-license', '--format=json']' returned non-zero exit status 1.

```
Looks like Speedtest is expecting speedtest --accept-gdpr, which it is not receiving. Possibly only happening at startup. How can I fix this?

**Comment by loganmarchione** [comment]
Nothing you can do, I can fix this tonight and publish a new version. 

They published a new version of the speedtest app which requires the new flag.

**Comment by loganmarchione** [comment]
@SteynGuelen Ah ok, I missed this detail earlier. You're on [v1](https://github.com/loganmarchione/docker-speedtest-influxdb) of this container, but there is a [v2](https://github.com/loganmarchione/docker-speedtest-influxdbv2) that has the `--accept-gdpr` flag ([here](https://github.com/loganmarchione/docker-speedtest-influxdbv2/blob/master/speedtest.py#L54)).

v2 works with InfluxDB 1.8 and 2.x, while this version (v1) only works with InfluxDB v1.x. I would highly recommend you test and migrate to the v2 container, since this v1 container is dependent on an [obsolete Python library](https://github.com/influxdata/influxdb-python). I'll eventually stop maintaining this version and delete the images from DockerHub.

Regardless, I've added the `--accept-gdpr` flag to a new version [0.6.1](https://hub.docker.com/r/loganmarchione/docker-speedtest-influxdb/tags) container. Please test and let me know if I can close this out.

**Comment by SteynGuelen** [comment]
The update is functional, works as intended now. Will upgrade to V2 later today. Thanks for the quick actions!
